pool:
  vmImage: ubuntu-latest

stages:
  - stage: 'Install'
    jobs:
    - job: install
      steps:
      - script: |
         python3 -m pip install --user virtualenv
         python3 -m venv /tmp/requirements
         source /tmp/requirements/bin/activate
         pip install -r requirements.txt

  - stage: 'BlackDuck_Code_Scan'
    jobs:
    - job: detect
      steps:
      - task: SynopsysDetectTask@9
        inputs:
          BlackDuckService: 'BlackDuck'
          DetectArguments: |
            --detect.project.name=requirements  
            --detect.project.version.name=azure1 
            --blackduck.trust.cert=true  
            --detect.detector.search.depth=100  
            --detect.tools=DETECTOR  
            --detect.detector.search.continue=true
          DetectVersion: 'latest'  