trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Install the requirements.txt dependencies!
  displayName: 'Install the requirements.txt dependencies'

- script: |
    python -m pip install -r requirements.txt
  displayName: 'Install the requirements.txt dependencies'