stages:
  - stage: 'Install'
    jobs:
    - job: install
      steps:
      - script: |
         python3 -m pip install --user virtualenv
         python3 -m venv /tmp/requirements1
         source /tmp/requirements1/bin/activate
         python setup.py install
         pip install -r requirements.txt
         bash <(curl -s -L https://detect.synopsys.com/detect9.sh) --blackduck.url=https://accenture-test.app.blackduck.com/ --blackduck.trust.cert=true --blackduck.api.token=NzIxOWQ5ZGUtMzNiZi00OGNiLTgwNmQtMzFjNzU4MThlZTJmOmQ0YTMwM2I1LTIwMjktNDBmYy1hZTM4LWE0MDA2MzcyZDQ1Mw== --detect.project.name=requirements1 --detect.project.version.name=1.0
